// scripts/fetch-fonts.mjs
//
// Downloads the Inter and Poppins weights the app uses into public/fonts/ and
// writes the matching @font-face rules to src/fonts.css.
//
// Why self-host at all: style.css used to `@import` these from Google Fonts.
// Lighthouse measured that request as 785ms of render-blocking time and 65.7 kB
// of transfer — more bytes than the entire JS bundle — and Workbox cannot
// precache a cross-origin stylesheet, so an offline first paint fell back to
// system fonts. For an app whose whole claim is working offline, the typography
// was the last thing still reaching for the network on the render path.
//
// Only the `latin` subset is taken. Google serves eight (cyrillic, devanagari,
// greek, vietnamese and so on) for a UI that is English-only.
//
//   node scripts/fetch-fonts.mjs

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT      = join(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR  = join(ROOT, 'public', 'fonts');
const CSS_OUT   = join(ROOT, 'src', 'fonts.css');

// A modern UA is required, or Google serves ttf instead of woff2.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
         + '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

const SOURCE = 'https://fonts.googleapis.com/css2'
             + '?family=Inter:wght@400;500;600;700;800'
             + '&family=Poppins:wght@400;500;600;700;800'
             + '&display=swap';

/** Split the returned CSS into blocks tagged with their subset comment. */
function parseFaces(css) {
  const faces = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let m;
  while ((m = re.exec(css)) !== null) {
    const [, subset, body] = m;
    const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
    const weight = /font-weight:\s*(\d+)/.exec(body)?.[1];
    const style  = /font-style:\s*(\w+)/.exec(body)?.[1] ?? 'normal';
    const url    = /url\((https:[^)]+)\)/.exec(body)?.[1];
    const range  = /unicode-range:\s*([^;]+);/.exec(body)?.[1];
    if (family && weight && url) faces.push({ subset, family, weight, style, url, range });
  }
  return faces;
}

const res = await fetch(SOURCE, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
const faces = parseFaces(await res.text()).filter(f => f.subset === 'latin');

if (faces.length === 0) throw new Error('No latin faces parsed — did the CSS format change?');

mkdirSync(FONT_DIR, { recursive: true });

// Group by URL. Inter is a variable font, so Google returns the *same* file for
// every weight and the browser fetches it once. Writing one file per weight
// produced five byte-identical copies and 240 kB of duplicate downloads — worse
// than the CDN it was replacing. Poppins is static and genuinely has one file
// per weight.
const byUrl = new Map();
for (const face of faces) {
  if (!byUrl.has(face.url)) byUrl.set(face.url, []);
  byUrl.get(face.url).push(face);
}

const rules = [];
let total = 0;

for (const [url, group] of byUrl) {
  const first    = group[0];
  const weights  = group.map(f => Number(f.weight)).sort((a, b) => a - b);
  const variable = group.length > 1;

  const slug = variable
    ? `${first.family.toLowerCase()}-variable.woff2`
    : `${first.family.toLowerCase()}-${first.weight}.woff2`;

  const bin = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(join(FONT_DIR, slug), bin);
  total += bin.length;
  console.log(`  ${slug.padEnd(24)} ${String(bin.length).padStart(7)} bytes  ${
    variable ? `variable ${weights[0]}–${weights[weights.length - 1]}` : `weight ${first.weight}`}`);

  rules.push(
    `@font-face {`,
    `  font-family: '${first.family}';`,
    `  font-style: ${first.style};`,
    // A range on a variable font lets the browser interpolate any weight in it
    // from the single file, instead of five rules pointing at the same bytes.
    `  font-weight: ${variable ? `${weights[0]} ${weights[weights.length - 1]}` : first.weight};`,
    // swap: render immediately in the fallback and restyle when the file lands,
    // rather than holding text hostage to a font on a slow connection.
    `  font-display: swap;`,
    `  src: url('/fonts/${slug}') format('woff2');`,
    ...(first.range ? [`  unicode-range: ${first.range};`] : []),
    `}`,
    ``,
  );
}

writeFileSync(CSS_OUT, [
  '/* src/fonts.css — GENERATED by scripts/fetch-fonts.mjs. Do not edit by hand. */',
  '/*',
  ' * Self-hosted so the render path has no third-party dependency and Workbox can',
  ' * precache the files, which is what makes typography survive offline.',
  ' *',
  ' * Inter and Poppins are both SIL Open Font License 1.1, which permits',
  ' * redistribution: https://openfontlicense.org',
  ' */',
  '',
  ...rules,
].join('\n'));

console.log(`\n  ${faces.length} faces, ${(total / 1024).toFixed(1)} kB total`);
console.log(`  wrote ${CSS_OUT}`);
